### ISSUE TITLE
Order.Get, SerializationException

### ISSUE THREAD

**Issue by nvsoares** [XiaoFaye/WooCommerce.NET#620] opened 2021-06-09 14:10 UTC
Hello.
When I call the method Orders.Get to obtain an order, I am getting the following exception on the deserialization:

###  System.Runtime.Serialization.SerializationException:
'There was an error deserializing the object of type WooCommerceNET.WooCommerce.v3.Order. End element 'display_value' from namespace '' expected. Found element 'woocommerce_method_instance_id' from namespace ''.'

Attached file with response json string: [54103.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/6624306/54103.txt)

Note: With v0.8.2 it was working just fine.

Can you help?

**Comment by timeframederek** [comment] 2021-06-10 01:39
Hi this is a duplicate of open issue orderlines and couponlines returning JSON array not string,

See #618

**Comment by firestormza** [comment] 2021-06-14 09:11
This was fixed with PR #600 You'll have to get the source and build it.

**Comment by Gareth-Lee-PBH** [comment] 2021-06-17 16:21
Hi, is the fix scheduled for release via the nuget package any time soon?

**Closed** 2023-03-30 00:32 UTC
