### ISSUE TITLE
Error in Batch removes

### ISSUE THREAD

**Issue by andraschris** [XiaoFaye/WooCommerce.NET#581] opened 2021-03-16 09:46 UTC
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version (5.6.2), WooCommerce version (5.0) and WooCommerce.NET version ( 0.8.2.0)

The function when i try to update 1-1 is ok

1. But, when i try to delete all categories
  Dim CategoryBatch As WooCommerceNET.Base.BatchObject(Of ProductCategory)
  CategoryBatch = LsC.Cast(Of WooCommerceNET.Base.BatchObject(Of ProductCategory))
  Await wc.Category.DeleteRange(CategoryBatch)
					
i am getting this error 
 '<CastIterator>d__97`1[WooCommerceNET.Base.BatchObject`1[WooCommerceNET.WooCommerce.v3.ProductCategory]]' σε αντικείμενο τύπου 'WooCommerceNET.Base.BatchObject`1[WooCommerceNET.WooCommerce.v3.ProductCategory]'.

2. and when i try to delete all products

 Dim ProductBatch As WooCommerceNET.Base.BatchObject(Of Product)
 ProductBatch = LsPr.Cast(Of WooCommerceNET.Base.BatchObject(Of Product))
 Await wc.Product.DeleteRange(ProductBatch)

i am getting this error 				
Δεν είναι δυνατή η μετατροπή αντικειμένου τύπου '<CastIterator>d__97`1[WooCommerceNET.Base.BatchObject`1[WooCommerceNET.WooCommerce.v3.Product]]' σε αντικείμενο τύπου 'WooCommerceNET.Base.BatchObject`1[WooCommerceNET.WooCommerce.v3.Product]'.

**Comment by XiaoFaye** [comment] 2021-03-17 08:41
Could be a duplicate of #523 , could you please update to version 0.8.3 and try again?

**Comment by andraschris** [comment] 2021-03-17 08:59
Thank you!

**Closed** 2021-03-22 07:20 UTC
