### ISSUE TITLE
Good Morning I'm trying to use your wrapper and I'm getting an invalid signature response.

### ISSUE THREAD

**Issue by bensongwalker** [XiaoFaye/WooCommerce.NET#71] opened 2016-12-17 10:18 UTC
### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version, WooCommerce version and WooCommerce.NET version

- Steps to replicate the issue

- Details of the error message if there is any

**Comment by XiaoFaye** [comment] 2016-12-17 11:11
Please provide more details

**Comment by bensongwalker** [comment] 2016-12-17 15:41
I'm sorry I didnt mean to post that

**Comment by bensongwalker** [comment] 2016-12-20 20:40
Sorry it took me a while to get back to this. First of all I'll start off by apologizing because I'm a newbie here. I'm trying to create a windows service in vb.net that will pull products and orders from Wordpress. We have WordPress and WOO installed on an IIS Server here at the shop. WP is at 4.7 and WC is at 2.6.9. I've enabled the rest.api and generated the consumer key and secret.  I've never worked with your wrapper or WC for that matter and I'm encountering issues. It appears that I have 3 differen't legacy versions installed
the path to the legacy folders is:
D:\iservices\Testing\wp-content\plugins\woocommerce\includes\api\legacy\v1 or v2 or v3

Here is my code and response when using version 3

As soon as I try to fetch a list of products my code throws an exception. I'll only post some of it because it's quite lengthy. It looks as if it's just spitting back the php code at me.

Imports System.Data
Imports System.Threading
Imports System.Diagnostics
Imports WooCommerceNET
Imports System.Net.Http
Imports System.Net
Imports System.IO
Public Class woo_interface
    Private pull_timer As System.Threading.Timer
    Private pull_interval As Integer
    Dim rest As WooCommerceNET.RestAPI
    Dim wc As WooCommerceNET.WooCommerce.Legacy.WCObject
    Protected Overrides Sub OnStart(ByVal args() As String)
        pull_timer = New Timer(New TimerCallback(AddressOf Me.NightlyPull), Nothing, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite)
        pull_timer.Change(30 * (1000), System.Threading.Timeout.Infinite)       ' changed to start after 30 seconds 

    End Sub

    Protected Overrides Sub OnStop()
        ' Add code here to perform any tear-down necessary to stop your service.
    End Sub
    Private Async Sub NightlyPull(ByVal State As Object)
        Dim s_url As String = My.Settings.dovetailUrl
        Dim s_key As String = My.Settings.consumerKey
        Dim s_secret As String = My.Settings.consumerKey
        Dim product As New WooCommerceNET.WooCommerce.Legacy.Product
        Dim productList As WooCommerceNET.WooCommerce.Legacy.ProductList
        pull_timer.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite)
        EventLog.WriteEntry("Woo_interface", "Pull Ended", EventLogEntryType.SuccessAudit)


        rest = New WooCommerceNET.RestAPI(s_url, s_key, s_secret)
        Try
            wc = New WooCommerceNET.WooCommerce.Legacy.WCObject(rest)
            productList = Await wc.GetProducts()
            For Each product In productList
                Debug.Print(product.name)
            Next

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

        pull_interval = My.Settings.pullMinutes * My.Settings.pullInterval
        pull_timer.Change(pull_interval, System.Threading.Timeout.Infinite)
    End Sub
End Class
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
the exception that's thrown
<!DOCTYPE html>
<html lang="en-US" class="no-js no-svg">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">

<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>
<title>Page not found &#8211; Testing Environment</title>
<meta name='robots' content='noindex,follow' />
<link rel='dns-prefetch' href='//fonts.googleapis.com' />
<link rel='dns-prefetch' href='//s.w.org' />
<link href='https://fonts.gstatic.com' crossorigin rel='preconnect' />
<link rel="alternate" type="application/rss+xml" title="Testing Environment &raquo; Feed" href="http://testing.cissltd.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="Testing Environment &raquo; Comments Feed" href="http://testing.cissltd.com/comments/feed/" />
		<script type="text/javascript">
			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.2.1\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/testing.cissltd.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.7"}};

**Comment by XiaoFaye** [comment] 2016-12-20 21:06
Your exception message shows that your WooCommerce API is not working correctly, some plugins or your custom codes might have changed the REST API default behavior.

BTW: 
Could you please try to use the latest V1 rest api? As I'm not maintaining the legacy ones anymore.
http://www.yourstore.co.nz/wp-json/wc/v1/

**Comment by bensongwalker** [comment] 2016-12-20 21:27
Thanks for the quick response. I don’t see the wp-json folder under our store front. Do I need to download that?

**Comment by XiaoFaye** [comment] 2016-12-20 21:35
No, you don't need to have an actual folder;

**Comment by bensongwalker** [comment] 2016-12-20 21:52
Ok I'll give it a shot thanks

**Comment by bensongwalker** [comment] 2016-12-21 13:03
Ok, I changed my code and pointed the url to the new api. However still getting an exception this time a different one however
At the bottom

Imports System.Data
Imports System.Threading
Imports System.Diagnostics
Imports WooCommerceNET
Imports System.Net.Http
Imports System.Net
Imports System.IO
Public Class woo_interface
    Private pull_timer As System.Threading.Timer
    Private pull_interval As Integer
    Dim rest As WooCommerceNET.RestAPI
    Dim wc As WooCommerceNET.WooCommerce.WCObject
    Protected Overrides Sub OnStart(ByVal args() As String)
        pull_timer = New Timer(New TimerCallback(AddressOf Me.NightlyPull), Nothing, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite)
        pull_timer.Change(30 * (1000), System.Threading.Timeout.Infinite)       ' changed to start after 30 seconds 

    End Sub

    Protected Overrides Sub OnStop()
        ' Add code here to perform any tear-down necessary to stop your service.
    End Sub
    Private Async Sub NightlyPull(ByVal State As Object)
        Dim s_url As String = My.Settings.dovetailUrl
        Dim s_key As String = My.Settings.consumerKey
        Dim s_secret As String = My.Settings.consumerKey
        Dim product As New WooCommerceNET.WooCommerce.Product
        Dim productList As WooCommerceNET.WooCommerce.ProductList
        pull_timer.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite)
        EventLog.WriteEntry("Woo_interface", "Pull Ended", EventLogEntryType.SuccessAudit)


        rest = New WooCommerceNET.RestAPI(s_url, s_key, s_secret)
        Try
            wc = New WooCommerceNET.WooCommerce.WCObject(rest)
            productList = Await wc.GetProducts()
            For Each product In productList
                Debug.Print(product.name)
            Next

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

        pull_interval = My.Settings.pullMinutes * My.Settings.pullInterval
        pull_timer.Change(pull_interval, System.Threading.Timeout.Infinite)
    End Sub
End Class


Exception
{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}

**Comment by XiaoFaye** [comment] 2016-12-21 19:55
Can you pull out the correct data using Postman?

**Comment by markldavison** [comment] 2016-12-21 19:59
Hi,

Thank you for your response. I have this working now and it is great!


Kind Regards,

Mark Davison

**Comment by XiaoFaye** [comment] 2016-12-21 22:38
@markldavison  Good to hear that, I will close the issue.

**Comment by bensongwalker** [comment] 2016-12-22 16:08
Some how my thread got crossed with markldavison. I'm still searching for a solution to my problem and don't consider my question closed.

**Comment by markldavison** [comment] 2016-12-22 16:51
I have just tried some code to list the products. This works for me within a console app:

```
   Private Async Sub FetchProducts()
        Dim rest As RestAPI = New RestAPI(strURL, strK, strS)
        Dim wc As WCObject = New WCObject(rest)

        Try

            Dim productslist As List(Of Product) = Await wc.GetProducts()

            Console.WriteLine(productslist.Count)

            For Each product In productslist
                Console.WriteLine(product.id)
                Console.WriteLine(product.name)

                Console.WriteLine("============================")
            Next


        Catch ex As Exception
            Console.WriteLine(ex.Message)
        End Try

    End Sub
```
Do you want to see if you can get the above code to work? strURL, strK, strS are the URL, Key and Secret for your site. The only Imports I have used are:

```
Imports WooCommerceNET
Imports WooCommerceNET.WooCommerce
```

If you create a new console app, put the imports at the top then use this as your Sub Main():

  ```
 Sub Main()

        FetchProducts()

        Console.ReadLine()
    End Sub
```
You should see all your products listed. This code works so if you cannot get it to then the problem is somewhere else. I recommend starting with a simple console app first just to prove you can get it working.

**Comment by markldavison** [comment] 2016-12-22 16:56
Also, I am using https to connect i.e. https://YOURSITE/wp-json/wc/v1/

Looking at your error I would also check the URL for the call and that the key and secret are correct.

**Comment by bensongwalker** [comment] 2016-12-22 18:53
I tried your code and I’m still getting errors if I use https I get “Consumer secret invalid” If I use http I get “Invalid signature”

 

I’m a third party contractor here and don’t have access to the site so I put out a request to the hosting company to validate the url for me. Hopefully I’ll hear back from them soon

Thanks for the quick response I’ll try not to bother you too much. Have a great holiday and again thanks for the code sample.

-BW

**Comment by markldavison** [comment] 2016-12-22 19:02
Ok, I would suspect some problem with the setup of your server. If you just paste the URL into a browser do you get a response?

The above code works so the client library is also working from vb just fine. I can only think that it must be something to do with the hosting / server config. I would recommend https so you need to get this working - I do know the key and secret can be sent in a different way so it is always possible there is something with the client library when not using https but I can't test this.

Let me know if I can give any further help.

**Comment by markldavison** [comment] 2016-12-22 20:06
What happens if you paste the following URL into your browser? If this does not work then your not going to get anything from your own code:

`https://www.YOURDOMAIN.com/wp-json/wc/v1/Products?consumer_key=YOUR_KEY&consumer_secret=YOUR_SECRET`

If everything is set up correct on the server then you should a JSON listing for your products. Note, this will only work over https. From what you have said before, you should get “Consumer secret invalid” which would suggest a configuration issue or a credential issue.

Once you have this returning your data in the browser, you should then be able to run the VB.net code with the same URL, Key and Secret and you would get the results back.

**Comment by bensongwalker** [comment] 2016-12-22 20:40
Hmm seem to be getting somewhere

https doesn’’t work at all but http returns

 

{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

**Comment by bensongwalker** [comment] 2016-12-22 20:40
Sorry it returns both on http and https

{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

**Comment by markldavison** [comment] 2016-12-22 20:44
I get the same when I use http. This does not allow the key and secret to be passed on the querystring. I also get this over https if I give an incorrect key.

It will work in the browser if everything is set up properly and you are using the correct URL, key and secret. Once you have this over https then the VB code / Client Library should work fine.

I guess the first question is should your site be accessible over https and, if so, the key or secret must be incorrect.

**Comment by bensongwalker** [comment] 2016-12-22 20:57
I’ll ask and thanks again for your help. I’m pretty sure the key and secret are correct I was remoted in when they generated it. 

-BW

**Comment by bensongwalker** [comment] 2016-12-22 20:59
We created a customer account for myself with read permissions and generated the key. Is that’s all that’s needed and https?

**Comment by XiaoFaye** [comment] 2016-12-22 21:24
@bensongwalker  Have you tried to set the authorizeHeader to false?

**Comment by bensongwalker** [comment] 2016-12-22 21:40
Do I have to install the Woocommerce.Authorize.Net Aim extension to enable that?

**Comment by XiaoFaye** [comment] 2016-12-22 21:48
@bensongwalker  No, that is no need.

**Comment by bensongwalker** [comment] 2016-12-22 23:44
Is that a property in your wrapper?

**Comment by XiaoFaye** [comment] 2016-12-23 00:19
please have a look at the changes doc in the project GitHub page.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Dec 23, 2016 at 12:44 PM +1300, "bensongwalker" <notifications@github.com<mailto:notifications@github.com>> wrote:

Is that a property in your wrapper?

**Comment by markldavison** [comment] 2016-12-23 11:27
He means try this:

`Dim rest As RestAPI = New RestAPI(strURL, strK, strS, False)`

**Comment by bensongwalker** [comment] 2016-12-23 13:21
Ok thanks

**Comment by bensongwalker** [comment] 2016-12-23 14:30
Hmm… not an option I must of installed an older package?

**Comment by markldavison** [comment] 2016-12-23 14:33
I have version 0.6.1 installed. If you are not using that version then I would update your installation and try again.

**Comment by bensongwalker** [comment] 2016-12-23 14:35
I thought I did install that version but I’ll download again. Thanks

**Comment by bensongwalker** [comment] 2016-12-23 15:05
Thanks guys I’m in… you made my Christmas, Happy Holidays.

-BW

**Closed** 2017-01-08 10:42 UTC
