### ISSUE TITLE
Adding products with dimensions does not work

### ISSUE THREAD

**Issue by TomasAxelsson** [XiaoFaye/WooCommerce.NET#62] opened 2016-12-04 10:44 UTC
Wordpress version: 4.6.1–sv_SE
WooCommerce.NET: 0.5.3

First: Thanks for making this very useful piece of code! :)

Im trying to use WooCommerce.NET to add products, everything works fine execept of adding dimensions.
I don't get any error messages but the dimensions never show up in WooCommerce. I have tried all ways that I can think of using the dimension and the dimensionlist objects, but I can't get it to work.

Here is an example of my code that adds the product just fine, but do not add the dimension data:

            Product p = new Product()
            {
                name = "test product 8",
                short_description = "Short desc product 8",
                description = "Looong desc product 8",
                regular_price = 15,

                date_modified = DateTime.Now,
                weight = 10,

                dimensions = new DimensionList { new Dimension { height = "10" }, new Dimension { width = "20" }, new Dimension { length = "30" } },

                sku = "Product nr 8"

            };
            await wc.PostProduct(p);

**Comment by XiaoFaye** [comment] 2016-12-04 22:31
Hi, the issue is because the data type of dimensions property in Product has been set to a List incorrectly, it should be Dimension.

If you are using the source code, you can make the below changes:

Line 278 in Product.cs
Before:
`public List<Dimension> dimensions { get; set; }`

After:
`public Dimension dimensions { get; set; }`

Then change your code to:
`dimensions = new Dimension() { height = "100", width = "100", length = "100" }`

Or you can wait for the next version in NuGet, this fix will be included in the next version.

Thanks.

**Comment by TomasAxelsson** [comment] 2016-12-07 11:09
Great thanks, good work!

**Closed** 2016-12-07 11:09 UTC
